	#
      #            Group - 13
      #    Vishwas Jain      13CS10053
      #    Rahul Sonais      13CS10049
      #            Assignment-6
      #            Make File


compile: GR13_13CS10053_13CS10049_Assignment6_atm.c GR13_13CS10053_13CS10049_Assignment6_client.c GR13_13CS10053_13CS10049_Assignment6_master.c
	gcc -o master GR13_13CS10053_13CS10049_Assignment6_master.c
	gcc -o atm GR13_13CS10053_13CS10049_Assignment6_atm.c
	gcc -o client GR13_13CS10053_13CS10049_Assignment6_client.c
